print("Integer equivalent of B is ", ord('B'))
print("Integer equivalent of C is ", ord('C'))
print("Integer equivalent of D is ", ord('D'))
print("Integer equivalent of b is ", ord('b'))
print("Integer equivalent of c is ", ord('c'))
print("Integer equivalent of d is ", ord('d'))
print("Integer equivalent of 0 is ", ord('0'))
print("Integer equivalent of 1 is ", ord('1'))
print("Integer equivalent of 2 is ", ord('2'))
print("Integer equivalent of $ is ", ord('$'))
print("Integer equivalent of * is ", ord('*'))
print("Integer equivalent of + is ", ord('+'))
print("Integer equivalent of space is ", ord(' '))
