first_number = int(input("Enter numbers from 0 to 5 and press enter after each entering: "))
second_int = int(input())
third_int = int(input())
fourth_int = int(input())
fifth_int = int(input())
sixth_int = int(input())
print("number\t", "square\t", "cube\t")
print(first_number,"\t\t", first_number ** 2, "\t\t", first_number ** 3)
print(second_int,"\t\t", second_int ** 2, "\t\t", second_int ** 3)
print(third_int,"\t\t", third_int ** 2, "\t\t", third_int ** 3)
print(fourth_int,"\t\t", fourth_int ** 2, "\t\t", fourth_int ** 3)
print(fifth_int,"\t\t", fifth_int ** 2, "\t\t", fifth_int ** 3)
print(sixth_int,"\t\t", sixth_int ** 2, "\t", sixth_int ** 3)
